/**
 * 🔥 Banco de palabras clave para identificar la colección correcta a partir de la consulta del usuario
 */
export const queryKeywords = {
  restaurant: [
    'restaurant',
    'food',
    'eat',
    'dining',
    'meal',
    'cuisine',
    'vegan',
    'vegetarian',
    'organic',
    'steak',
    'burger',
    'hamburger',
    'cheeseburger',
    'fast food',
    'shawarma',
    'falafel',
    'kebab',
    'taco',
    'burrito',
    'nachos',
    'hot dog',
    'grill',
    'bbq',
    'ribs',
    'roast',
    'meat',
    'chicken',
    'beef',
    'lamb',
    'pork',
    'seafood',
    'fish',
    'ceviche',
    'sushi',
    'nigiri',
    'sashimi',
    'makis',
    'poke',
    'salmon',
    'tuna',
    'oysters',
    'lobster',
    'shrimp',
    'clams',
    'mussels',
    'crab',
    'pizza',
    'pizzeria',
    'mozzarella',
    'neapolitan',
    'pasta',
    'spaghetti',
    'lasagna',
    'ravioli',
    'risotto',
    'gnocchi',
    'italian',
    'argentinian',
    'mexican',
    'thai',
    'indian',
    'chinese',
    'japanese',
    'korean',
    'mediterranean',
    'french',
    'spanish',
    'middle eastern',
    'lebanese',
    'brazilian',
    'peruvian',
    'colombian',
    'chilean',
    'barbecue',
    'asado',
    'smoked',
    'roasted',
    'gourmet',
    'tasting menu',
    'wine',
    'cocktail',
    'sommelier',
    'brunch',
    'dinner',
    'lunch',
    'breakfast',
    'buffet',
    'tapas',
    'fine dining',
    'casual dining',
  ],
  cafe: [
    'cafe',
    'coffee',
    'espresso',
    'latte',
    'mocha',
    'cappuccino',
    'americano',
    'macchiato',
    'flat white',
    'cold brew',
    'iced coffee',
    'frappuccino',
    'turkish coffee',
    'french press',
    'aeropress',
    'drip coffee',
    'tea',
    'matcha',
    'bubble tea',
    'chai',
    'herbal tea',
    'green tea',
    'black tea',
    'oolong',
    'earl grey',
    'pastry',
    'bakery',
    'bread',
    'croissant',
    'bagel',
    'brioche',
    'muffin',
    'cupcake',
    'cookie',
    'brownie',
    'cheesecake',
    'pie',
    'macaron',
    'tiramisu',
    'flan',
    'crepe',
    'waffle',
    'toast',
    'sandwich',
    'brunch',
    'breakfast',
    'dessert',
    'patisserie',
    'artisan coffee',
    'coffee shop',
    'specialty coffee',
  ],
  party: [
    'party',
    'nightclub',
    'club',
    'bar',
    'pub',
    'cocktail bar',
    'rooftop bar',
    'lounge',
    'speakeasy',
    'dj',
    'event',
    'festival',
    'concert',
    'live music',
    'karaoke',
    'dance',
    'rave',
    'disco',
    'electronic music',
    'house music',
    'techno',
    'reggaeton',
    'salsa',
    'bachata',
    'latin night',
    'hip hop',
    'trap',
    'open bar',
    'vip',
    'bottle service',
    'shots',
    'happy hour',
    'after party',
  ],
  tour: [
    'tour',
    'trip',
    'sightseeing',
    'excursion',
    'guide',
    'landmark',
    'monument',
    'museum',
    'castle',
    'cathedral',
    'hiking',
    'adventure',
    'jungle',
    'safari',
    'trekking',
    'rafting',
    'scuba diving',
    'snorkeling',
    'paragliding',
    'bungee jumping',
    'hot air balloon',
    'wine tasting',
    'food tour',
    'historical site',
    'cultural experience',
    'city tour',
    'bike tour',
    'boat tour',
    'cruise',
    'national park',
    'nature reserve',
    'eco-tourism',
  ],
  temple: [
    'temple',
    'church',
    'mosque',
    'synagogue',
    'cathedral',
    'basilica',
    'shrine',
    'chapel',
    'monastery',
    'abbey',
    'gurdwara',
    'pagoda',
    'stupa',
    'spiritual site',
    'holy place',
    'religious site',
    'pilgrimage',
    'prayer',
    'meditation',
    'worship',
    'buddhist temple',
    'hindu temple',
  ],
  accomodation: [
    'hotel',
    'hostel',
    'bnb',
    'bed and breakfast',
    'stay',
    'resort',
    'room',
    'lodging',
    'guesthouse',
    'vacation rental',
    'apartment rental',
    'boutique hotel',
    'motel',
    'eco lodge',
    'beachfront hotel',
    'luxury hotel',
    'spa resort',
    'cabin',
    'cottage',
    'glamping',
    'camping',
    'rv park',
    'all-inclusive',
    'business hotel',
    'pet-friendly hotel',
    'family hotel',
    'adult-only hotel',
  ],
};

import diacritics from 'diacritics';

/**
 * 🔍 Detecta la colección adecuada en función de las palabras clave en la consulta del usuario.
 * @param {string} query - Consulta en texto plano.
 * @returns {string | null} - Nombre de la colección detectada o `null` si no se encuentra coincidencia.
 */
export const detectCollection = async query => {
  const lowerQuery = diacritics.remove(query.toLowerCase());

  for (const [collection, keywords] of Object.entries(queryKeywords)) {
    if (keywords.some(keyword => lowerQuery.includes(keyword))) {
      return collection;
    }
  }
  return null; // Si no se encuentra ninguna coincidencia
};
